#server:
#  port: 8081
#graphiql:
#  enabled: true
#  mapping: /graphqlp
#graphql:
#  servlet:
#    mapping: /graphql
#    corsEnabled: false
server:
  port: 6060
  servlet:
    context-path: /graphql-learnings
